from UI.pages.requirements.add_requirement import AddRequirementPage
from UI.pages.requirements.mass_add_requirement import MassAddRequirementPage
from UI.pages.requirements.requirement_view import RequirementView
from UI.pages.requirements.edit_requirement import EditRequirementPage